<a href="https://colab.research.google.com/github/EneruJ/H3CoursPython/blob/Exercices/PyAlgo13_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Veuillez saisir 2 nombres !")
x = int(input("Nombre n°1 : "))
y = int(input("Nombre n°2 : "))


if(x < 0 and y < 0) or (x > 0 and y > 0):
  print("Nombre positif !")
else:
  print("Nombre négatif !")


Veuillez saisir 2 nombres !
Nombre n°1 : 5
Nombre n°2 : -5
Nombre négatif !


In [ ]:
print("Veuillez saisir le nombre de départ !")
depart = int(input("Nombre de départ : "))
resultat = 0

for x in range(depart+1):
 resultat += x

print("Le résultat est "+str(resultat))

Veuillez saisir le nombre de départ !
Nombre de départ : 5
Le résultat est 15


In [ ]:
tab = [1,2,3,4,5]
resultat = 0

for x in tab:
  resultat += x

print("Le résultat est "+str(resultat))

Le résultat est 15


In [ ]:
tab1 = [1,2,3,4,5]
tab2 = [1,2,3,4,5]
resultat = 0

for x in tab1:
  for y in tab2:
    resultat += (x*y)

print("Le résultat est "+str(resultat))

Le résultat est 225


In [ ]:
tab_string = input("Tableau de valeurs : ")
tab = tab_string.split(",")
print(tab)
val_max = 0
index_max = 0
for index, value in enumerate(tab):
  if(int(value) > int(val_max)):
    val_max = value
    index_max = index
print("La valeur max est "+str(val_max))
print("L'index de la valeur max est "+str(index_max))


Tableau de valeurs : 1,5,7,8,2,12
['1', '5', '7', '8', '2', '12']
La valeur max est 12
L'index de la valeur max est 5


In [ ]:
tab_string = input("Tableau de notes : ")
tab = tab_string.split(",")
moyenne = 0
nb_val_supp = 0

for x in tab:
  moyenne += int(x)

moyenne = moyenne / len(tab)

for x in tab:
 if(int(x)>moyenne):
   nb_val_supp+= 1

print("La moyenne est de "+str(moyenne))
print("Le nombre de personnes au dessus de la moyenne est de "+str(nb_val_supp))

Tableau de notes : 2,4,6,8,10
La moyenne est de 6.0
Le nombre de personnes au dessus de la moyenne est de 2


In [ ]:
import numpy as np

v1 = np.array([[1,2,3],[4,1,2]])
v2 = np.array([[3,4,7],[2,4,3],[2,1,2]])

v_final = np.matmul(v1,v2)
print(v_final)


[[13 15 19]
 [18 22 35]]


In [ ]:
tab_sort_croissant = [15,4,8,6,8,1,9,3]
tab_sort_decroissant = [15,4,8,6,8,1,9,3]

tab_sort_croissant.sort()
tab_sort_decroissant.sort(reverse=True)

print(tab_sort_croissant)
print(tab_sort_decroissant)




[1, 3, 4, 6, 8, 8, 9, 15]
[15, 9, 8, 8, 6, 4, 3, 1]


In [ ]:
print("Veuillez saisir le nombre de départ !")
depart = int(input("Nombre de départ : "))
factorielle = 1

for x in range(1, depart+1):
  factorielle = factorielle * x

print("La factorielle de",depart,"est",factorielle)

Veuillez saisir le nombre de départ !
Nombre de départ : 4
La factorielle de 4 est 24


In [ ]:
import numpy as np

matriceA = np.array([[1,2,0],[4,3,-1]])

matriceB = np.array([[3,4,5],[1,2,3]])

matriceC = matriceA * matriceB

print("Matrice A\n",matriceA)
print("Matrice B\n",matriceB)
print("Matrice C\n",matriceC)

Matrice A
 [[ 1  2  0]
 [ 4  3 -1]]
Matrice B
 [[3 4 5]
 [1 2 3]]
Matrice C
 [[ 3  8  0]
 [ 4  6 -3]]


In [ ]:
def FIBO(n):
    if n > 1:
        return FIBO(n-1) + FIBO(n-2)
    return n
for x in range(10):
    print(FIBO(x))

0
1
1
2
3
5
8
13
21
34


In [17]:
reel = 2
resultat_suite = 0
i = 0
while (resultat_suite > reel) == False:
  i = i + 1
  resultat_suite += 1/i
  print("N :",i,"\nTotal de la suite :",resultat_suite)
  if(resultat_suite > reel):
    print("Plus petit entier permettant de dépasser le réel",reel,":", i)
  


N : 1 
Total de la suite : 1.0
N : 2 
Total de la suite : 1.5
N : 3 
Total de la suite : 1.8333333333333333
N : 4 
Total de la suite : 2.083333333333333
Plus petit entier permettant de dépasser le réel 2 : 4
